const words = [
    'JS',
    'React',
    'React Native',
    'C#',
    'F#',
    '.Net Core',
    'GraphQL',
    'NodeJS',
    'Microservices',
    'Azure',
    'SQL Server',
    'SignalR',
    'DevOps',
    'Identity',
    'Tooling',
    'Design System',
    'Architecture',
    'Semantic HTML',
    'A11y',
    'i18n',
    'CSS',
    'People Management',
    'Leadership',
    'Mentoring',
    'Team Building',
]

export default words
